language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"

env:
  - CONTAO_VERSION=~4.4.0

sudo: false

before_install:
  - phpenv config-add travis.php.ini

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer require contao/core $CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --dev --no-interaction

script: ant -keep-going

# Hack to make the repo non shallow - we can not use a shallow repository.
git:
  depth: 2147483647
