services:
    cca.dc-general.contao_frontend.view.build_widget_listener:
        class: ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\DefaultWidgetBuilder
        tags:
          - { name: kernel.event_listener, event: 'dc-general.contao-frontend.build-widget', method: handleEvent }
        arguments:
          - '@cca.dc-general.scope-matcher'

    cca.dc-general.contao_frontend.handle_submit_listener:
        class: ContaoCommunityAlliance\DcGeneral\ContaoFrontend\Listener\HandleSubmitListener
        tags:
          - { name: kernel.event_listener, event: 'dc-general.contao-frontend.handle-submit', method: handleEvent }
        arguments:
          - '@cca.dc-general.scope-matcher'

    cca.dc-general.contao_frontend.create_handler:
        class: ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\ActionHandler\CreateHandler
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }

    cca.dc-general.contao_frontend.edit_handler:
        class: ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\ActionHandler\EditHandler
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }

    cca.dc-general.contao_frontend.copy_handler:
        class: ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\ActionHandler\CopyHandler
        arguments:
            - "@cca.dc-general.scope-matcher"
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }
