services:
    cca.dc-general.contao_frontend.action_listener:
        class: ContaoCommunityAlliance\DcGeneral\ContaoFrontend\Listener\ActionListener
        tags:
          - { name: kernel.event_listener, event: 'dc-general.action', method: handleEvent, priority: 10 }
        arguments:
          - '@cca.dc-general.scope-matcher'

    cca.dc-general.contao_frontend.view.build_widget_listener:
        class: ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\DefaultWidgetBuilder
        tags:
          - { name: kernel.event_listener, event: 'dc-general.contao-frontend.build-widget', method: handleEvent }
        arguments:
          - '@cca.dc-general.scope-matcher'

    cca.dc-general.contao_frontend.handle_submit_listener:
        class: ContaoCommunityAlliance\DcGeneral\ContaoFrontend\Listener\HandleSubmitListener
        tags:
          - { name: kernel.event_listener, event: 'dc-general.contao-frontend.handle-submit', method: handleEvent }
        arguments:
          - '@cca.dc-general.scope-matcher'
